version: '3.7'

services:
  localstack:
    image: localstack/localstack:0.14.1
    container_name: sqs-poller-locastack-aws
    healthcheck:
      test:
        - CMD
        - bash
        - -c
        - awslocal sqs get-queue-url --queue-name ccs-compliance-customers
      interval: 1s
      timeout: 10s
      retries: 5
      start_period: 60s
    environment:
      - SERVICES=sqs,sns
      - AWS_ACCESS_KEY_ID=1
      - AWS_SECRET_ACCESS_KEY=1
      - AWS_DEFAULT_REGION=us-east-1
      - DATA_DIR=/tmp/localstack/data
      - LEGACY_PERSISTENCE=0
      - LS_LOG=error
    ports:
      - 4566:4566
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes: 
      - ./build/localstack-init:/docker-entrypoint-initaws.d
