version: '3.7'

services:
  localstack:
    image: localstack/localstack:0.11.0
    container_name: sqs-poller-locastack-aws
    environment:
      - SERVICES=sqs,sns
      - DEFAULT_REGION=us-east-1
      - DATA_DIR=/tmp/localstack/data
    ports:
      - "4566:4566"

volumes:
  localstack-data:
    name: localstack-data