name: Build

on:
  pull_request:
    branches:
      master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 9.0.000
    - name: Build with dotnet
      run: dotnet build --configuration Release
