name: Publish Nuget pre-release package

on: 
  pull_request:
    branches:
      dev

jobs:
  build:
    name: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        
      - name: Build
        run: dotnet build --configuration Release --version-suffix -prerelease-$(date +%Y%m%d%H%M%S)
        shell: bash

      - name: Publish Nuget pre-release package
        run: dotnet nuget push src/SqsPoller/bin/Release/SqsPoller.*.*.*-prerelease-*.nupkg -k oy2mgzjo62rb3ctp2kbah4lppabszm4e3fl2yzoz7hbpyq -s https://api.nuget.org/v3/index.json
        shell: bash