name: Unit Tests

on:
  pull_request:
    branches:
      master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 9.0.000
      - name: Run Unit Tests 
        run: dotnet test ./test/SqsPoller.Tests.Unit/SqsPoller.Tests.Unit.csproj